#!/bin/bash

# Copyright 2002 Markus Grunwald */
# All other Copyrights (especially Qt and mysql) belong to their owners */

#This file is part of divelog.
#
#divelog is free software; you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation; either version 2 of the License, or
#(at your option) any later version.
#
#divelog is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with divelog; if not, write to the Free Software
#Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

# $Id: tables,v 1.12 2002/05/15 09:27:51 grunwalm Exp $ 

mysql -h zaphod -u markus --password='ArPPCa' divelog-test <<EOF
drop table diver;
create table diver (
    number  INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(20) NOT NULL,
    last_name VARCHAR(30),
    brevet VARCHAR(10),
    street VARCHAR(40),
    house_number VARCHAR(6),
    zip INTEGER UNSIGNED,
    place VARCHAR(20),
    phone VARCHAR(20),
    email VARCHAR(130),
    UNIQUE( first_name, last_name, street, house_number, zip )
);

drop table divecomputer;
create table divecomputer(
    serial_number VARCHAR(16) PRIMARY KEY,
    diver_number INTEGER UNSIGNED NOT NULL REFERENCES diver,
    name VARCHAR(30) 
);

drop table divetype;
create table divetype (
    number  INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    description VARCHAR(20),
    UNIQUE ( description )
);

drop table filling_station;
create table filling_station (
    number  INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    stationname VARCHAR(20) NOT NULL,
    first_name  VARCHAR(20),
    last_name   VARCHAR(30),
    UNIQUE ( stationname )
);

drop table dive;
create table dive (
    number INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    date DATETIME NOT NULL,
    sync INTEGER UNSIGNED,
    diver_number INTEGER UNSIGNED NOT NULL REFERENCES diver,
    place VARCHAR(100) NOT NULL,
    location VARCHAR(100),
    altitude_mode DOUBLE NOT NULL,
    water_temperature DOUBLE NOT NULL,
    start_pressure DOUBLE NOT NULL,
    end_pressure DOUBLE NOT NULL,
    surface_intervall DOUBLE NOT NULL,
    max_depth DOUBLE NOT NULL,
    length TIME NOT NULL,
    profile BLOB, 
    log TEXT,
    partner_diver_number INTEGER UNSIGNED NOT NULL REFERENCES diver,
    weather VARCHAR(20),
    sight   VARCHAR(20),
    lead  FLOAT,
    air_temperature DOUBLE,
    dive_type INTEGER UNSIGNED REFERENCES divetype,
    filling_station_number INTEGER UNSIGNED NOT NULL REFERENCES filling_station,
    bottle_number INTEGER UNSIGNED NOT NULL,    
    UNIQUE ( date, diver_number ),
    KEY ( date, diver_number )
);
EOF
    
    
